In [2]:
import pandas as pd

data = {
"Name": [
    "Alice", "Bob", "Charlie", "David", "Evelyn",
    "Frank", "Grace", "Henry", "Isla", "Jack",
    "Karen", "Leo", "Mia", "Noah", "Olivia",
    "Paul", "Quinn", "Ruby", "Sam", "Tina"
],
"Age": [25, 32, 37, 29, 41, 28, 34, 45, 26, 31, 39, 27, 33, 36, 30, 42, 24, 38, 35, 29],
"Department": [
    "HR", "Engineering", "Sales", "Marketing", "Engineering",
    "Finance", "Support", "Operations", "HR", "Sales",
    "Engineering", "Support", "Marketing", "Finance", "Operations",
    "Engineering", "HR", "Sales", "Support", "Marketing"
],
"Salary": [
    50000, 75000, 62000, 58000, 80000,
    54000, 52000, 70000, 51000, 64000,
    82000, 53000, 60000, 56000, 68000,
    79000, 49500, 65500, 54500, 61000
],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
View the first five rows of the DataFrame.

In [3]:
df.head()

      Name  Age   Department  Salary
0    Alice   25           HR   50000
1      Bob   32  Engineering   75000
2  Charlie   37        Sales   62000
3    David   29    Marketing   58000
4   Evelyn   41  Engineering   80000

<h3>Exercise 2</h3>
View the last five rows of the DataFrame.

In [4]:
df.tail()

     Name  Age   Department  Salary
15   Paul   42  Engineering   79000
16  Quinn   24           HR   49500
17   Ruby   38        Sales   65500
18    Sam   35      Support   54500
19   Tina   29    Marketing   61000

<h3>Exercise 3</h3>
Get basic info about the DataFrame.

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        20 non-null     str
 1   Age         20 non-null     int64
 2   Department  20 non-null     str
 3   Salary      20 non-null     int64
dtypes: int64(2), str(2)
memory usage: 772.0 bytes

<h3>Exercise 4</h3>
Check the shape of the DataFrame.

In [6]:
df.shape

(20, 4)

<h2>Exercise Set 2: Indexing with .loc[] and .iloc[]</h2>
Use this starter code in your own environment:

In [7]:
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(df.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

<h3>Exercise 1</h3>
Use .loc to get the name and age of the passenger with index 12.

In [8]:
df.loc[12:12, ['Name', 'Age']]

                              Name   Age
12  Saundercock, Mr. William Henry  20.0

<h3>Exercise 2</h3>
Use .iloc to get the first 5 rows and first 3 columns.

In [9]:
df.iloc[0:5,0:3]

   PassengerId  Survived  Pclass
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

<h3>Exercise 3</h3>
Use .loc to get all passengers in 1st class who are female.

In [10]:
df.loc[(df['Pclass'] == 1) & (df['Sex'] == 'female')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C
...,...,...,...,...,...,...,...,...,...,...,...,...
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S

<h3>Exercise 4</h3>
Use .iloc to get the age of the 10th passenger (by position).

In [11]:
df.iloc[9, 5]

np.float64(14.0)

<h3>Exercise 5</h3>
Use .loc to get the Fare and Survived values for passengers with index 100 to 105.

In [12]:
df.loc[100:105, ['Fare', 'Survived']]

        Fare  Survived
100   7.8958         0
101   7.8958         0
102  77.2875         0
103   8.6542         0
104   7.9250         0
105   7.8958         0

<h2>Exercise Set 3: Summary Tools</h2>
Use this starter code in your own environment:

<h3>Exercise 1</h3>
Summarize the numeric columns.

In [13]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

<h3>Exercise 2</h3>
Use .value_counts() to see counts for embarkation ports.

In [14]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

<h3>Exercise 3</h3>
Use .value_counts() to count passenger classes.

In [15]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

<h3>Exercise 4</h3>
Show the average (mean) age of passengers.

In [16]:
df['Age'].mean()

np.float64(29.69911764705882)

<h3>Exercise 5</h3>
Show the maximum fare paid.

In [17]:
df['Fare'].max()

np.float64(512.3292)

<h3>Exercise 6</h3>
Show how many unique names are in the dataset.

In [18]:
df['Name'].nunique()

891

<h3>Exercise 7</h3>
Show counts for values in the Sex column.

In [19]:
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

<h3>Exercise 8</h3>
Show how many unique values are in each column.

In [20]:
df.nunique()

PassengerId    891
Survived         2
Pclass           3
Name           891
Sex              2
Age             88
SibSp            7
Parch            7
Ticket         681
Fare           248
Cabin          147
Embarked         3
dtype: int64

<h2>Section 2: Clean & Tidy Data</h2>

<h3>Exercise Set 1: Dropping Data</h3>
Use this starter code in your own environment:

In [21]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "David"],
"Age": [25, 30, 35, 40],
"City": ["NYC", "LA", "Chicago", "Miami"],
"Email": ["a@example.com", "b@example.com", "c@example.com", "d@example.com"],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
Drop the Email column and store the result in a new variable.

In [22]:
drop_email = df.drop('Email', axis=1)

<h3>Exercise 2</h3>
Drop the row with index 2 in place.

In [23]:
df.drop(2)

    Name  Age   City          Email
0  Alice   25    NYC  a@example.com
1    Bob   30     LA  b@example.com
3  David   40  Miami  d@example.com

<h3>Exercise 3</h3>
Drop the City and Email columns, and assign the result back to df.

In [24]:
df = df.drop(columns=['City','Email'])

<h3>Exercise 4</h3>
Drop the first and last row, and store the result in df_trimmed.

In [25]:
df_trimmed = df.iloc[1:-1]

<h2>Exercise Set 2: Missing Data</h2>
Use this starter code in your own environment:

In [26]:
import pandas as pd
import numpy as np

data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
"Age": [25, np.nan, 35, 40, None],
"City": ["NYC", "LA", None, "Miami", "Boston"],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
View the first 5 rows of the DataFrame.

In [27]:
df.head()

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

<h3>Exercise 2</h3>
Show where values are missing.

In [29]:
df.isna()

    Name    Age   City
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

<h3>Exercise 3</h3>
Count missing values by column.

In [41]:
df.isna().sum()

Name    0
Age     2
City    1
dtype: int64

<h3>Exercise 4</h3>
Drop rows with missing data.

In [43]:
df.dropna()

    Name   Age   City
0  Alice  25.0    NYC
3  David  40.0  Miami

<h3>Exercise 6</h3>
Drop columns with missing data.

In [44]:
df

      Name   Age    City
0    Alice  25.0     NYC
1      Bob   NaN      LA
2  Charlie  35.0     NaN
3    David  40.0   Miami
4      Eva   NaN  Boston

In [45]:
df.dropna(axis=1)

      Name
0    Alice
1      Bob
2  Charlie
3    David
4      Eva

<h3>Exercise 8</h3>
Fill missing Age values with the mean.

In [52]:
df['Age'] = df['Age'].fillna(df['Age'].mean())
df

      Name        Age    City
0    Alice  25.000000     NYC
1      Bob  33.333333      LA
2  Charlie  35.000000     NaN
3    David  40.000000   Miami
4      Eva  33.333333  Boston

<h3>Exercise 9</h3>
Fill missing City values with "Unknown".

In [54]:
df['City'] = df['City'].fillna('Unknown')
df

      Name        Age     City
0    Alice  25.000000      NYC
1      Bob  33.333333       LA
2  Charlie  35.000000  Unknown
3    David  40.000000    Miami
4      Eva  33.333333   Boston

<h2>Exercise Set 3: Duplicates</h2>
Use this starter code in your own environment:

In [55]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie", "Alice", "Bob", "Diana"],
"Age": [25, 30, 35, 25, 30, 40],
"City": ["NYC", "LA", "SF", "NYC", "LA", "NYC"],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
Find which rows are duplicates across all columns.

In [56]:
df.duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

<h3>Exercise 2</h3>
Drop duplicate rows, keeping the first occurrence.

In [58]:
df.drop_duplicates(keep="first")

      Name  Age City
0    Alice   25  NYC
1      Bob   30   LA
2  Charlie   35   SF
5    Diana   40  NYC

<h3>Exercise 3</h3>
Drop duplicate rows, keeping only the last occurrence.

In [59]:
df.drop_duplicates(keep="last")

      Name  Age City
2  Charlie   35   SF
3    Alice   25  NYC
4      Bob   30   LA
5    Diana   40  NYC

<h3>Exercise 4</h3>
Drop all duplicates, removing both the original and duplicate rows.

In [61]:
df.drop_duplicates(keep=False)

      Name  Age City
2  Charlie   35   SF
5    Diana   40  NYC

<h2>Section 3: Data Wrangling Essentials</h2>
<h3>Exercise Set 1: Renaming Columns</h3>
Use this starter code in your own environment:

In [66]:
import pandas as pd

data = {
"fname": ["Alice", "Bob", "Charlie"],
"lname": ["Smith", "Jones", "Brown"],
"ctry": ["USA", "Canada", "UK"],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
Change fname to FirstName and lname to LastName.

In [71]:
df.rename({'fname': 'FirstName','lname':'LastName'},axis=1, inplace=True)
df.head()

  FirstName LastName    ctry
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

<h3>Exercise 2</h3>
Change all column names to: ['FirstName', 'LastName', 'Country']

In [72]:
df.rename({'fname': 'FirstName','lname':'LastName','ctry':'Country'},axis=1, inplace=True)
df.head()

  FirstName LastName Country
0     Alice    Smith     USA
1       Bob    Jones  Canada
2   Charlie    Brown      UK

<h2>Exercise Set 2: Reordering Columns</h2>
Use this starter code in your own environment:

In [101]:
import pandas as pd

data = {
"Name": ["Alice", "Bob", "Charlie"],
"Dept": ["HR", "Finance", "IT"],
"Sal": [60000, 70000, 80000],
}

df = pd.DataFrame(data)

<h3>Exercise 1</h3>
Rename Dept to Department and Sal to Salary.

In [102]:
df.rename({'Dept': 'Department','Sal':'Salary'},axis=1, inplace=True)
df.head()

      Name Department  Salary
0    Alice         HR   60000
1      Bob    Finance   70000
2  Charlie         IT   80000

<h3>Exercise 2</h3>
Reorder columns so Salary appears first, followed by Name and Department.

In [ ]:
column_to_move = df.pop('Salary')
df.insert(0, "Salary", column_to_move)

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

<h3>Exercise 3</h3>
Print the updated DataFrame.

In [105]:
df

   Salary     Name Department
0   60000    Alice         HR
1   70000      Bob    Finance
2   80000  Charlie         IT

<h2>Exercise Set 3: GroupBy and Agg</h2>
Use this starter code in your own environment:

In [2]:
import pandas as pd

data = {
"Store": ["A", "A", "A", "B", "B", "C", "C", "C", "C"],
"Product": ["Apples", "Oranges", "Bananas", "Apples", "Bananas", "Oranges", "Apples", "Bananas", "Bananas"],
"Sales": [100, 80, 90, 120, 110, 60, 95, 85, 75],
"Profit": [30, 25, 20, 40, 35, 15, 32, 22, 18],
}

df = pd.DataFrame(data)
print(df.head())

  Store  Product  Sales  Profit
0     A   Apples    100      30
1     A  Oranges     80      25
2     A  Bananas     90      20
3     B   Apples    120      40
4     B  Bananas    110      35

<h3>Exercise 1</h3>
Group the data by Store and use .agg() to find the average Sales and average Profit for each store.

In [12]:
df.groupby(by='Store').agg({
    'Sales':'mean',
    'Profit': 'mean'
})

        Sales  Profit
Store
A       90.00   25.00
B      115.00   37.50
C       78.75   21.75

<h3>Exercise 2</h3>
Group by Product and get the maximum Sales and minimum Profit.

In [13]:
df.groupby('Product').agg({
    'Sales':'max',
    'Profit':'min'
})

         Sales  Profit
Product
Apples     120      30
Bananas    110      18
Oranges     80      15

<h3>Exercise 3</h3>
Group by Store and return the average Sales and maximum Profit, but name the columns Avg_Sales and Max_Profit.

In [15]:
df.groupby('Store').agg(Avg_Sales=('Sales','max'), Max_Profit=('Profit','max'))

       Avg_Sales  Max_Profit
Store
A            100          30
B            120          40
C             95          32

<h3>Exercise 4</h3>
BONUS: Group by both Store and Product, and find the total Sales using .agg().

In [20]:
df.groupby(['Store','Product']).agg('Sales').sum()

Store  Product
A      Apples     100
       Bananas     90
       Oranges     80
B      Apples     120
       Bananas    110
C      Apples      95
       Bananas    160
       Oranges     60
Name: Sales, dtype: int64

<h3>Exercise Set 4: Joining</h3>
Use this starter code in your own environment:

In [ ]:
import pandas as pd

df_customers = pd.DataFrame({
"CustomerName": ["Alice", "Bob", "Charlie"]
}, index=[101, 102, 103])

df_orders = pd.DataFrame({
"OrderTotal": [250, 300, 400]
}, index=[101, 102, 103])

<h3>Exercise 1</h3>
Join df_orders to df_customers on the index.

<h3>Exercise 2</h3>
Add a new column to df_customers with city data from df_cities.